package by.gsu.epamlab.constants;

public enum ActionConstants {

    TRACK, ACTOR, TAG, TRACK_ACTOR, TRACK_TAG, ACTOR_TAG, LOGIN, USER, USER_TRACK, USER_ACTOR, USER_TAG, DELETE_TRACK, DELETE_ACTOR, DELETE_TAG, DELETE_TRACK_ACTOR, DELETE_TRACK_TAG, DELETE_ACTOR_TAG;

}
